# Generated by Django 3.0.2 on 2020-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=35)),
                ('cat_img', models.ImageField(upload_to='')),
                ('cat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='desserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_name', models.CharField(max_length=35)),
                ('des_img', models.ImageField(upload_to='')),
                ('des_country', models.CharField(max_length=25)),
                ('des_instr', models.TextField()),
                ('des_ingreds', models.TextField()),
                ('des_ingamt', models.TextField()),
                ('des_youtube', models.TextField()),
                ('des_source', models.TextField()),
            ],
        ),
    ]
